data:
  paths:
    outputDir: "src/generated/data"
    jsonDir: "src/generated/data/json"
    mapsDir: "src/generated/data/maps"
    typesDir: "@/generated/data/languages"
    flatDir: "src/generated/data/flat"
    manifestsDir: "src/generated/data/manifests"
    gettersDir: "src/generated/getters/"

  sourcePaths:
    gettersDir: "src/transform/accessors/"