data:
  paths:
    outputDir: "src/generated/data"
    jsonDir: "src/generated/data/json"
    mapsDir: "src/generated/data/maps"
    typesDir: "@/generated/data/languages"
    flatDir: "src/generated/data/flat"
    manifestsDir: "src/generated/data/manifests"
    arraysDir: "src/generated/data/arrays"
    gettersDir: "src/generated/getters/"
    predicatesDir: "src/generated/predicates/"

  sourcePaths:
    gettersDir: "src/transform/accessors/"
    predicatesDir: "src/transform/predicates/"