// AUTOGENERATED from languages.yml
// This file is automatically generated - DO NOT EDIT MANUALLY
// Generated with constraints:
// {
//   "allowFlexibleTypes": false,
//   "itemsPerSegment": 50,
//   "maxArrayLiteralItems": 5000,
//   "maxLiteralValues": 5000,
//   "minItemsForSplit": 20,
//   "minLanguagesForNamedType": 0,
//   "minUsagePercent": 0,
//   "naming": {
//     "fields": [
//       {
//         "field": "name",
//         "type": "LanguageName"
//       }
//     ],
//     "language": "Language",
//     "languageName": "LanguageName",
//     "secondaryPrefix": "",
//     "secondarySuffix": "Relax"
//   },
//   "options": null,
//   "out": {
//     "common": {
//       "dir": {
//         "alias": "@/generated/types/common",
//         "rel": "src/generated/types/common"
//       },
//       "file": {
//         "ext": ".ts",
//         "name": "language-types.generated"
//       }
//     },
//     "usage": {
//       "dir": {
//         "alias": "@/generated/types/usage",
//         "rel": "src/generated/types/usage"
//       },
//       "file": {
//         "ext": ".ts",
//         "name": "usage-types.generated"
//       }
//     }
//   },
//   "secondary": {
//     "allowFlexibleTypes": true,
//     "enabled": true,
//     "useReadonlyArrays": true
//   },
//   "showExamples": 3,
//   "showFieldStats": true,
//   "source_paths": {
//     "types": {
//       "branded": {
//         "dir": {
//           "alias": "@/types/",
//           "rel": "src/types/"
//         },
//         "file": {
//           "ext": ".ts",
//           "name": "branded.types"
//         }
//       }
//     }
//   },
//   "splitLargeTypes": true,
//   "usage": {
//     "skip_should_generate_type": true
//   },
//   "useReadonlyArrays": true
// }
// Total languages: 8
// Total fields: 12

export type { OptionalBrand } from "@/types/branded.types";

// Segment definitions for large types

export type AceMode = "asciidoc" | "c_cpp" | "markdown" | "text";
export type Aliases = readonly "ags"[];
export type CodemirrorMimeType = "application/pgp" | "text/x-c++src";
export type CodemirrorMode = "asciiarmor" | "clike";
export type Color = "#2ACCA8" | "#34EB6B" | "#38761D" | "#73a0c5" | "#814CCC" | "#B9D9B9" | "#B9D9FF";
export type Extensions = readonly (
	| ".2da"
	| ".adoc"
	| ".aidl"
	| ".apib"
	| ".asc"
	| ".asciidoc"
	| ".ash"
	| ".bsl"
	| ".os"
	| ".pub"
)[];
export type Interpreters = readonly "aidl"[];
export type LanguageId = 0 | 2 | 5 | 22 | 298 | 387204628 | 451700185 | 852099832;
export type LanguageName =
	| "1C Enterprise"
	| "2-Dimensional Array"
	| "AGS Script"
	| "AIDL"
	| "API Blueprint"
	| "AsciiDoc"
	| "KoLmafia ASH"
	| "Public Key";
export type TmScope =
	| "none"
	| "source.2da"
	| "source.aidl"
	| "source.ash"
	| "source.bsl"
	| "source.c++"
	| "text.html.asciidoc"
	| "text.html.markdown.source.gfm.apib";
export type Type = "data" | "markup" | "programming" | "prose";
export type Wrap = true;

export type Language = {
	ace_mode: AceMode;
	aliases?: Aliases;
	codemirror_mime_type?: CodemirrorMimeType;
	codemirror_mode?: CodemirrorMode;
	color?: Color;
	extensions: Extensions;
	interpreters?: Interpreters;
	language_id: LanguageId;
	name: LanguageName;
	tm_scope: TmScope;
	type: Type;
	wrap?: Wrap;
};

export type AceModeRelax = ("asciidoc" | "c_cpp" | "markdown" | "text") | (string & {});
export type AliasesRelax = readonly ("ags" | (string & {}))[];
export type CodemirrorMimeTypeRelax = ("application/pgp" | "text/x-c++src") | (string & {});
export type CodemirrorModeRelax = ("asciiarmor" | "clike") | (string & {});
export type ColorRelax =
	| ("#2ACCA8" | "#34EB6B" | "#38761D" | "#73a0c5" | "#814CCC" | "#B9D9B9" | "#B9D9FF")
	| (string & {});
export type ExtensionsRelax = readonly (
	| (".2da" | ".adoc" | ".aidl" | ".apib" | ".asc" | ".asciidoc" | ".ash" | ".bsl" | ".os" | ".pub")
	| (string & {})
)[];
export type InterpretersRelax = readonly ("aidl" | (string & {}))[];
export type LanguageIdRelax = (0 | 2 | 5 | 22 | 298 | 387204628 | 451700185 | 852099832) | (number & {});
export type LanguageNameRelax =
	| (
			| "1C Enterprise"
			| "2-Dimensional Array"
			| "AGS Script"
			| "AIDL"
			| "API Blueprint"
			| "AsciiDoc"
			| "KoLmafia ASH"
			| "Public Key"
	  )
	| (string & {});
export type TmScopeRelax =
	| (
			| "none"
			| "source.2da"
			| "source.aidl"
			| "source.ash"
			| "source.bsl"
			| "source.c++"
			| "text.html.asciidoc"
			| "text.html.markdown.source.gfm.apib"
	  )
	| (string & {});
export type TypeRelax = ("data" | "markup" | "programming" | "prose") | (string & {});
export type WrapRelax = true;

export type LanguageRelax = {
	ace_mode: AceModeRelax;
	aliases?: AliasesRelax;
	codemirror_mime_type?: CodemirrorMimeTypeRelax;
	codemirror_mode?: CodemirrorModeRelax;
	color?: ColorRelax;
	extensions: ExtensionsRelax;
	interpreters?: InterpretersRelax;
	language_id: LanguageIdRelax;
	name: LanguageNameRelax;
	tm_scope: TmScopeRelax;
	type: TypeRelax;
	wrap?: WrapRelax;
};

// Utility types
export type Languages = Record<LanguageName, Language>;
export type LanguageField = keyof Language;

/**
 * dictionary type that accepts any string key.
 *
 * useful as a fallback type for objects with unknown or dynamic keys.
 *
 * evolved from `FallbackForUnknownKeys`.
 *
 * @example
 * type Config = {
 *   knownSetting: string;
 * } & Dictionary<unknown>;
 */
export type Dictionary<T> = Record<string & {}, T>;

export type LanguagePropertyTypeName =
	| "AceMode"
	| "AceModeRelax"
	| "Aliases"
	| "AliasesRelax"
	| "CodemirrorMimeType"
	| "CodemirrorMimeTypeRelax"
	| "CodemirrorMode"
	| "CodemirrorModeRelax"
	| "Color"
	| "ColorRelax"
	| "Extensions"
	| "ExtensionsRelax"
	| "Interpreters"
	| "InterpretersRelax"
	| "Language"
	| "LanguageId"
	| "LanguageIdRelax"
	| "LanguageName"
	| "LanguageNameRelax"
	| "TmScope"
	| "TmScopeRelax"
	| "Type"
	| "TypeRelax"
	| "Wrap"
	| "WrapRelax";

// Type-safe accessors
export type GetLanguage<Name extends LanguageName> = Languages[Name];
export type GetLanguageField<Name extends LanguageName, Field extends LanguageField> = Languages[Name][Field];
export type GetLanguagesByType<Type extends Language["type"] extends infer T ? T : never> = {
	[K in LanguageName as Languages[K]["type"] extends Type ? K : never]: Languages[K];
};

// Field Statistics:
// ace_mode: used in 8/8 (100.0%) -> AceMode, 4 values
// aliases: used in 1/8 (12.5%) -> Aliases, array[1]
// codemirror_mime_type: used in 2/8 (25.0%) -> CodemirrorMimeType, 2 values
// codemirror_mode: used in 2/8 (25.0%) -> CodemirrorMode, 2 values
// color: used in 7/8 (87.5%) -> Color, 7 values
// extensions: used in 8/8 (100.0%) -> Extensions, array[10]
// interpreters: used in 1/8 (12.5%) -> Interpreters, array[1]
// language_id: used in 8/8 (100.0%) -> LanguageId, 8 values
// name: used in 8/8 (100.0%) -> LanguageName, 8 values
// tm_scope: used in 8/8 (100.0%) -> TmScope, 8 values
// type: used in 8/8 (100.0%) -> Type, 4 values
// wrap: used in 1/8 (12.5%) -> Wrap, 1 values

// Language Name Statistics:
// Total languages: 8
