import { stringify } from "safe-stable-stringify";

import type { Config } from "@/types/config.types";
import type { TypeGenConfig } from "@/types/gen-config.types";

const formatConfigAsComments = (config: TypeGenConfig): string[] => {
	const jsonStr = stringify(config, null, 2);
	return jsonStr.split("\n").map((line) => `// ${line}`);
};
//
const emitAutogenHeader = (source: string, config: Config, totals: { total: number; size: number }): string => {
	const { total, size } = totals;
	const now = new Date().toISOString();
	const configLines = formatConfigAsComments(config.type).join("\n");

	return [
		`// AUTOGENERATED from ${source}`,
		"// This file is automatically generated - DO NOT EDIT MANUALLY",
		`// Last updated: ${now}`,
		"// Generated with constraints:",
		configLines,
		`// Total languages: ${total}`,
		`// Total fields: ${size}`,
		"\n",
	].join("\n");
};

export { emitAutogenHeader };
