import type { TypeGenConfig } from "@/types/gen-config.types";

const formatConfigAsComments = (config: TypeGenConfig): string[] =>
	Object.entries(config).map(([k, v]) => `//   ${k}: ${JSON.stringify(v)}`);

//
const emitAutogenHeader = (source: string, config: TypeGenConfig, totals: { total: number; size: number }): string => {
	const { total, size } = totals;
	const now = new Date().toISOString();
	const configLines = formatConfigAsComments(config).join("\n");

	return [
		`// AUTOGENERATED from ${source}`,
		"// This file is automatically generated - DO NOT EDIT MANUALLY",
		`// Last updated: ${now}`,
		"// Generated with constraints:",
		configLines,
		`// Total languages: ${total}`,
		`// Total fields: ${size}`,
		"\n",
	].join("\n");
};

export { emitAutogenHeader };
